name: tfm_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.10
  - sqlite=3.41.1
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - ipykernel=6.15.0
  - ipython=8.12.0
  - pip:
    - pandas==1.5.3
    - mlflow==2.3.2
    - scikit-learn==1.2.2
    - matplotlib==3.7.1
    - seaborn==0.12.2
    - kaggle==1.5.13
    - numpy==1.23.5
    - imblearn
    - virtualenv